services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Almaty
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      NODE_ENV: production
      TZ: ${TZ:-Asia/Almaty}
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npx knex migrate:latest --knexfile knexfile.cjs &&
        node dist/index.js
      "

volumes:
  pgdata:
